//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#asset;
  pub(crate) mod r#cooldown;
  pub(crate) mod r#liquidity_pool;
  pub(crate) mod r#settings;
  pub(crate) mod r#user_permissions;

  pub use self::r#asset::*;
  pub use self::r#cooldown::*;
  pub use self::r#liquidity_pool::*;
  pub use self::r#settings::*;
  pub use self::r#user_permissions::*;

