/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link WithdrawRequest}
 * @category Accounts
 * @category generated
 */
export type WithdrawRequestArgs = {
  user: web3.PublicKey
  vault: web3.PublicKey
  receiptAmount: beet.bignum
  unlockDate: beet.bignum
}

export const withdrawRequestDiscriminator = [
  186, 239, 174, 191, 189, 13, 47, 196,
]
/**
 * Holds the data for the {@link WithdrawRequest} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class WithdrawRequest implements WithdrawRequestArgs {
  private constructor(
    readonly user: web3.PublicKey,
    readonly vault: web3.PublicKey,
    readonly receiptAmount: beet.bignum,
    readonly unlockDate: beet.bignum
  ) {}

  /**
   * Creates a {@link WithdrawRequest} instance from the provided args.
   */
  static fromArgs(args: WithdrawRequestArgs) {
    return new WithdrawRequest(
      args.user,
      args.vault,
      args.receiptAmount,
      args.unlockDate
    )
  }

  /**
   * Deserializes the {@link WithdrawRequest} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [WithdrawRequest, number] {
    return WithdrawRequest.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link WithdrawRequest} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<WithdrawRequest> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find WithdrawRequest account at ${address}`)
    }
    return WithdrawRequest.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, withdrawRequestBeet)
  }

  /**
   * Deserializes the {@link WithdrawRequest} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [WithdrawRequest, number] {
    return withdrawRequestBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link WithdrawRequest} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return withdrawRequestBeet.serialize({
      accountDiscriminator: withdrawRequestDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link WithdrawRequest}
   */
  static get byteSize() {
    return withdrawRequestBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link WithdrawRequest} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      WithdrawRequest.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link WithdrawRequest} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === WithdrawRequest.byteSize
  }

  /**
   * Returns a readable version of {@link WithdrawRequest} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      user: this.user.toBase58(),
      vault: this.vault.toBase58(),
      receiptAmount: (() => {
        const x = <{ toNumber: () => number }>this.receiptAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      unlockDate: (() => {
        const x = <{ toNumber: () => number }>this.unlockDate
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const withdrawRequestBeet = new beet.BeetStruct<
  WithdrawRequest,
  WithdrawRequestArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['user', beetSolana.publicKey],
    ['vault', beetSolana.publicKey],
    ['receiptAmount', beet.u64],
    ['unlockDate', beet.i64],
  ],
  WithdrawRequest.fromArgs,
  'WithdrawRequest'
)
