/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type DepositArgs = {
  vaultId: beet.bignum
  amount: beet.bignum
  isRewards: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const depositArgsBeet = new beet.BeetArgsStruct<DepositArgs>(
  [
    ['vaultId', beet.u64],
    ['amount', beet.u64],
    ['isRewards', beet.bool],
  ],
  'DepositArgs'
)
