//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `rlp` program ID.
  pub const RLP_ID: Pubkey = pubkey!("moCKzPuzFkiMfpVzCDqho13VzMW5cJgdE4gg29X2AmM");

