/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitializeOrderBookWrapper
 * @category generated
 */
export const initializeOrderBookWrapperStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'InitializeOrderBookWrapperInstructionArgs'
)
/**
 * Accounts required by the _initializeOrderBookWrapper_ instruction
 *
 * @property [_writable_] orderBook
 * @property [_writable_, **signer**] user
 * @category Instructions
 * @category InitializeOrderBookWrapper
 * @category generated
 */
export type InitializeOrderBookWrapperInstructionAccounts = {
  orderBook: web3.PublicKey
  user: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeOrderBookWrapperInstructionDiscriminator = [
  115, 77, 3, 192, 219, 103, 173, 226,
]

/**
 * Creates a _InitializeOrderBookWrapper_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeOrderBookWrapper
 * @category generated
 */
export function createInitializeOrderBookWrapperInstruction(
  accounts: InitializeOrderBookWrapperInstructionAccounts,
  programId = new web3.PublicKey('sSmYaKe6tj5VKjPzHhpakpamw1PYoJFLQNyMJD3PU37')
) {
  const [data] = initializeOrderBookWrapperStruct.serialize({
    instructionDiscriminator:
      initializeOrderBookWrapperInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.orderBook,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
