//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const RESTAKE_DISCRIMINATOR: [u8; 8] = [97, 161, 241, 167, 6, 32, 213, 53];

/// Accounts.
#[derive(Debug)]
pub struct Restake {
      
              
          pub signer: solana_pubkey::Pubkey,
          
              
          pub settings: solana_pubkey::Pubkey,
          
              
          pub permissions: Option<solana_pubkey::Pubkey>,
          
              
          pub liquidity_pool: solana_pubkey::Pubkey,
          
              
          pub lp_token: solana_pubkey::Pubkey,
          
              
          pub user_lp_account: solana_pubkey::Pubkey,
          
              
          pub asset: solana_pubkey::Pubkey,
          
              
          pub asset_mint: solana_pubkey::Pubkey,
          
              
          pub user_asset_account: solana_pubkey::Pubkey,
          
              
          pub pool_asset_account: solana_pubkey::Pubkey,
          
              
          pub oracle: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
          
              
          pub associated_token_program: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl Restake {
  pub fn instruction(&self, args: RestakeInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: RestakeInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(14+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.signer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.settings,
            false
          ));
                                                      if let Some(permissions) = self.permissions {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                permissions,
                false,
              ));
            } else {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::RLP_ID,
                false,
              ));
            }
                                                    accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.liquidity_pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.lp_token,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_lp_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.asset,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.asset_mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_asset_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool_asset_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = RestakeInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::RLP_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct RestakeInstructionData {
            discriminator: [u8; 8],
                        }

impl RestakeInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [97, 161, 241, 167, 6, 32, 213, 53],
                                                            }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for RestakeInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct RestakeInstructionArgs {
                  pub liquidity_pool_index: u8,
                pub amount: u64,
                pub min_lp_tokens: u64,
      }

impl RestakeInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `Restake`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` settings
                ///   2. `[optional]` permissions
          ///   3. `[]` liquidity_pool
                ///   4. `[writable]` lp_token
                ///   5. `[writable]` user_lp_account
          ///   6. `[]` asset
                ///   7. `[writable]` asset_mint
                ///   8. `[writable]` user_asset_account
                ///   9. `[writable]` pool_asset_account
          ///   10. `[]` oracle
                ///   11. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
                ///   12. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
                ///   13. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct RestakeBuilder {
            signer: Option<solana_pubkey::Pubkey>,
                settings: Option<solana_pubkey::Pubkey>,
                permissions: Option<solana_pubkey::Pubkey>,
                liquidity_pool: Option<solana_pubkey::Pubkey>,
                lp_token: Option<solana_pubkey::Pubkey>,
                user_lp_account: Option<solana_pubkey::Pubkey>,
                asset: Option<solana_pubkey::Pubkey>,
                asset_mint: Option<solana_pubkey::Pubkey>,
                user_asset_account: Option<solana_pubkey::Pubkey>,
                pool_asset_account: Option<solana_pubkey::Pubkey>,
                oracle: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                associated_token_program: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        liquidity_pool_index: Option<u8>,
                amount: Option<u64>,
                min_lp_tokens: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RestakeBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            #[inline(always)]
    pub fn settings(&mut self, settings: solana_pubkey::Pubkey) -> &mut Self {
                        self.settings = Some(settings);
                    self
    }
            /// `[optional account]`
#[inline(always)]
    pub fn permissions(&mut self, permissions: Option<solana_pubkey::Pubkey>) -> &mut Self {
                        self.permissions = permissions;
                    self
    }
            #[inline(always)]
    pub fn liquidity_pool(&mut self, liquidity_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.liquidity_pool = Some(liquidity_pool);
                    self
    }
            #[inline(always)]
    pub fn lp_token(&mut self, lp_token: solana_pubkey::Pubkey) -> &mut Self {
                        self.lp_token = Some(lp_token);
                    self
    }
            #[inline(always)]
    pub fn user_lp_account(&mut self, user_lp_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_lp_account = Some(user_lp_account);
                    self
    }
            #[inline(always)]
    pub fn asset(&mut self, asset: solana_pubkey::Pubkey) -> &mut Self {
                        self.asset = Some(asset);
                    self
    }
            #[inline(always)]
    pub fn asset_mint(&mut self, asset_mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.asset_mint = Some(asset_mint);
                    self
    }
            #[inline(always)]
    pub fn user_asset_account(&mut self, user_asset_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_asset_account = Some(user_asset_account);
                    self
    }
            #[inline(always)]
    pub fn pool_asset_account(&mut self, pool_asset_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool_asset_account = Some(pool_asset_account);
                    self
    }
            #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_pubkey::Pubkey) -> &mut Self {
                        self.oracle = Some(oracle);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
#[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.associated_token_program = Some(associated_token_program);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn liquidity_pool_index(&mut self, liquidity_pool_index: u8) -> &mut Self {
        self.liquidity_pool_index = Some(liquidity_pool_index);
        self
      }
                #[inline(always)]
      pub fn amount(&mut self, amount: u64) -> &mut Self {
        self.amount = Some(amount);
        self
      }
                #[inline(always)]
      pub fn min_lp_tokens(&mut self, min_lp_tokens: u64) -> &mut Self {
        self.min_lp_tokens = Some(min_lp_tokens);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = Restake {
                              signer: self.signer.expect("signer is not set"),
                                        settings: self.settings.expect("settings is not set"),
                                        permissions: self.permissions,
                                        liquidity_pool: self.liquidity_pool.expect("liquidity_pool is not set"),
                                        lp_token: self.lp_token.expect("lp_token is not set"),
                                        user_lp_account: self.user_lp_account.expect("user_lp_account is not set"),
                                        asset: self.asset.expect("asset is not set"),
                                        asset_mint: self.asset_mint.expect("asset_mint is not set"),
                                        user_asset_account: self.user_asset_account.expect("user_asset_account is not set"),
                                        pool_asset_account: self.pool_asset_account.expect("pool_asset_account is not set"),
                                        oracle: self.oracle.expect("oracle is not set"),
                                        token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        associated_token_program: self.associated_token_program.unwrap_or(solana_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
          let args = RestakeInstructionArgs {
                                                              liquidity_pool_index: self.liquidity_pool_index.clone().expect("liquidity_pool_index is not set"),
                                                                  amount: self.amount.clone().expect("amount is not set"),
                                                                  min_lp_tokens: self.min_lp_tokens.clone().expect("min_lp_tokens is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `restake` CPI accounts.
  pub struct RestakeCpiAccounts<'a, 'b> {
          
                    
              pub signer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub settings: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub permissions: Option<&'b solana_account_info::AccountInfo<'a>>,
                
                    
              pub liquidity_pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub lp_token: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_lp_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub asset: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub asset_mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_asset_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool_asset_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub oracle: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `restake` CPI instruction.
pub struct RestakeCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub signer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub settings: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub permissions: Option<&'b solana_account_info::AccountInfo<'a>>,
          
              
          pub liquidity_pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub lp_token: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_lp_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub asset: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub asset_mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_asset_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool_asset_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub oracle: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: RestakeInstructionArgs,
  }

impl<'a, 'b> RestakeCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: RestakeCpiAccounts<'a, 'b>,
              args: RestakeInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              signer: accounts.signer,
              settings: accounts.settings,
              permissions: accounts.permissions,
              liquidity_pool: accounts.liquidity_pool,
              lp_token: accounts.lp_token,
              user_lp_account: accounts.user_lp_account,
              asset: accounts.asset,
              asset_mint: accounts.asset_mint,
              user_asset_account: accounts.user_asset_account,
              pool_asset_account: accounts.pool_asset_account,
              oracle: accounts.oracle,
              token_program: accounts.token_program,
              associated_token_program: accounts.associated_token_program,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(14+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.settings.key,
            false
          ));
                                          if let Some(permissions) = self.permissions {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              *permissions.key,
              false,
            ));
          } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              crate::RLP_ID,
              false,
            ));
          }
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.liquidity_pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.lp_token.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_lp_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.asset.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.asset_mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_asset_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_asset_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = RestakeInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::RLP_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(15 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.signer.clone());
                        account_infos.push(self.settings.clone());
                        if let Some(permissions) = self.permissions {
          account_infos.push(permissions.clone());
        }
                        account_infos.push(self.liquidity_pool.clone());
                        account_infos.push(self.lp_token.clone());
                        account_infos.push(self.user_lp_account.clone());
                        account_infos.push(self.asset.clone());
                        account_infos.push(self.asset_mint.clone());
                        account_infos.push(self.user_asset_account.clone());
                        account_infos.push(self.pool_asset_account.clone());
                        account_infos.push(self.oracle.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.associated_token_program.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `Restake` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` settings
                ///   2. `[optional]` permissions
          ///   3. `[]` liquidity_pool
                ///   4. `[writable]` lp_token
                ///   5. `[writable]` user_lp_account
          ///   6. `[]` asset
                ///   7. `[writable]` asset_mint
                ///   8. `[writable]` user_asset_account
                ///   9. `[writable]` pool_asset_account
          ///   10. `[]` oracle
          ///   11. `[]` token_program
          ///   12. `[]` associated_token_program
          ///   13. `[]` system_program
#[derive(Clone, Debug)]
pub struct RestakeCpiBuilder<'a, 'b> {
  instruction: Box<RestakeCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RestakeCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(RestakeCpiBuilderInstruction {
      __program: program,
              signer: None,
              settings: None,
              permissions: None,
              liquidity_pool: None,
              lp_token: None,
              user_lp_account: None,
              asset: None,
              asset_mint: None,
              user_asset_account: None,
              pool_asset_account: None,
              oracle: None,
              token_program: None,
              associated_token_program: None,
              system_program: None,
                                            liquidity_pool_index: None,
                                amount: None,
                                min_lp_tokens: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      #[inline(always)]
    pub fn settings(&mut self, settings: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.settings = Some(settings);
                    self
    }
      /// `[optional account]`
#[inline(always)]
    pub fn permissions(&mut self, permissions: Option<&'b solana_account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.permissions = permissions;
                    self
    }
      #[inline(always)]
    pub fn liquidity_pool(&mut self, liquidity_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.liquidity_pool = Some(liquidity_pool);
                    self
    }
      #[inline(always)]
    pub fn lp_token(&mut self, lp_token: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lp_token = Some(lp_token);
                    self
    }
      #[inline(always)]
    pub fn user_lp_account(&mut self, user_lp_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_lp_account = Some(user_lp_account);
                    self
    }
      #[inline(always)]
    pub fn asset(&mut self, asset: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.asset = Some(asset);
                    self
    }
      #[inline(always)]
    pub fn asset_mint(&mut self, asset_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.asset_mint = Some(asset_mint);
                    self
    }
      #[inline(always)]
    pub fn user_asset_account(&mut self, user_asset_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_asset_account = Some(user_asset_account);
                    self
    }
      #[inline(always)]
    pub fn pool_asset_account(&mut self, pool_asset_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool_asset_account = Some(pool_asset_account);
                    self
    }
      #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.oracle = Some(oracle);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.associated_token_program = Some(associated_token_program);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn liquidity_pool_index(&mut self, liquidity_pool_index: u8) -> &mut Self {
        self.instruction.liquidity_pool_index = Some(liquidity_pool_index);
        self
      }
                #[inline(always)]
      pub fn amount(&mut self, amount: u64) -> &mut Self {
        self.instruction.amount = Some(amount);
        self
      }
                #[inline(always)]
      pub fn min_lp_tokens(&mut self, min_lp_tokens: u64) -> &mut Self {
        self.instruction.min_lp_tokens = Some(min_lp_tokens);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = RestakeInstructionArgs {
                                                              liquidity_pool_index: self.instruction.liquidity_pool_index.clone().expect("liquidity_pool_index is not set"),
                                                                  amount: self.instruction.amount.clone().expect("amount is not set"),
                                                                  min_lp_tokens: self.instruction.min_lp_tokens.clone().expect("min_lp_tokens is not set"),
                                    };
        let instruction = RestakeCpi {
        __program: self.instruction.__program,
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          settings: self.instruction.settings.expect("settings is not set"),
                  
          permissions: self.instruction.permissions,
                  
          liquidity_pool: self.instruction.liquidity_pool.expect("liquidity_pool is not set"),
                  
          lp_token: self.instruction.lp_token.expect("lp_token is not set"),
                  
          user_lp_account: self.instruction.user_lp_account.expect("user_lp_account is not set"),
                  
          asset: self.instruction.asset.expect("asset is not set"),
                  
          asset_mint: self.instruction.asset_mint.expect("asset_mint is not set"),
                  
          user_asset_account: self.instruction.user_asset_account.expect("user_asset_account is not set"),
                  
          pool_asset_account: self.instruction.pool_asset_account.expect("pool_asset_account is not set"),
                  
          oracle: self.instruction.oracle.expect("oracle is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          associated_token_program: self.instruction.associated_token_program.expect("associated_token_program is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct RestakeCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            signer: Option<&'b solana_account_info::AccountInfo<'a>>,
                settings: Option<&'b solana_account_info::AccountInfo<'a>>,
                permissions: Option<&'b solana_account_info::AccountInfo<'a>>,
                liquidity_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                lp_token: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_lp_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                asset: Option<&'b solana_account_info::AccountInfo<'a>>,
                asset_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_asset_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool_asset_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        liquidity_pool_index: Option<u8>,
                amount: Option<u64>,
                min_lp_tokens: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

