//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_DEPOSIT_CAP_DISCRIMINATOR: [u8; 8] = [175, 41, 137, 203, 27, 184, 245, 164];

/// Accounts.
#[derive(Debug)]
pub struct UpdateDepositCap {
      
              
          pub signer: solana_pubkey::Pubkey,
          
              
          pub admin: solana_pubkey::Pubkey,
          
              
          pub settings: solana_pubkey::Pubkey,
          
              
          pub liquidity_pool: solana_pubkey::Pubkey,
      }

impl UpdateDepositCap {
  pub fn instruction(&self, args: UpdateDepositCapInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdateDepositCapInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.signer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.admin,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.settings,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.liquidity_pool,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdateDepositCapInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::RLP_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateDepositCapInstructionData {
            discriminator: [u8; 8],
                  }

impl UpdateDepositCapInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [175, 41, 137, 203, 27, 184, 245, 164],
                                              }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdateDepositCapInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdateDepositCapInstructionArgs {
                  pub lockup_id: u64,
                pub new_cap: Option<u64>,
      }

impl UpdateDepositCapInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdateDepositCap`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` admin
          ///   2. `[]` settings
                ///   3. `[writable]` liquidity_pool
#[derive(Clone, Debug, Default)]
pub struct UpdateDepositCapBuilder {
            signer: Option<solana_pubkey::Pubkey>,
                admin: Option<solana_pubkey::Pubkey>,
                settings: Option<solana_pubkey::Pubkey>,
                liquidity_pool: Option<solana_pubkey::Pubkey>,
                        lockup_id: Option<u64>,
                new_cap: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateDepositCapBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin = Some(admin);
                    self
    }
            #[inline(always)]
    pub fn settings(&mut self, settings: solana_pubkey::Pubkey) -> &mut Self {
                        self.settings = Some(settings);
                    self
    }
            #[inline(always)]
    pub fn liquidity_pool(&mut self, liquidity_pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.liquidity_pool = Some(liquidity_pool);
                    self
    }
                    #[inline(always)]
      pub fn lockup_id(&mut self, lockup_id: u64) -> &mut Self {
        self.lockup_id = Some(lockup_id);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn new_cap(&mut self, new_cap: u64) -> &mut Self {
        self.new_cap = Some(new_cap);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdateDepositCap {
                              signer: self.signer.expect("signer is not set"),
                                        admin: self.admin.expect("admin is not set"),
                                        settings: self.settings.expect("settings is not set"),
                                        liquidity_pool: self.liquidity_pool.expect("liquidity_pool is not set"),
                      };
          let args = UpdateDepositCapInstructionArgs {
                                                              lockup_id: self.lockup_id.clone().expect("lockup_id is not set"),
                                                                  new_cap: self.new_cap.clone(),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_deposit_cap` CPI accounts.
  pub struct UpdateDepositCapCpiAccounts<'a, 'b> {
          
                    
              pub signer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub admin: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub settings: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub liquidity_pool: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_deposit_cap` CPI instruction.
pub struct UpdateDepositCapCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub signer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub admin: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub settings: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub liquidity_pool: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdateDepositCapInstructionArgs,
  }

impl<'a, 'b> UpdateDepositCapCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdateDepositCapCpiAccounts<'a, 'b>,
              args: UpdateDepositCapInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              signer: accounts.signer,
              admin: accounts.admin,
              settings: accounts.settings,
              liquidity_pool: accounts.liquidity_pool,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.admin.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.settings.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.liquidity_pool.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdateDepositCapInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::RLP_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.signer.clone());
                        account_infos.push(self.admin.clone());
                        account_infos.push(self.settings.clone());
                        account_infos.push(self.liquidity_pool.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdateDepositCap` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` admin
          ///   2. `[]` settings
                ///   3. `[writable]` liquidity_pool
#[derive(Clone, Debug)]
pub struct UpdateDepositCapCpiBuilder<'a, 'b> {
  instruction: Box<UpdateDepositCapCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateDepositCapCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdateDepositCapCpiBuilderInstruction {
      __program: program,
              signer: None,
              admin: None,
              settings: None,
              liquidity_pool: None,
                                            lockup_id: None,
                                new_cap: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin = Some(admin);
                    self
    }
      #[inline(always)]
    pub fn settings(&mut self, settings: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.settings = Some(settings);
                    self
    }
      #[inline(always)]
    pub fn liquidity_pool(&mut self, liquidity_pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.liquidity_pool = Some(liquidity_pool);
                    self
    }
                    #[inline(always)]
      pub fn lockup_id(&mut self, lockup_id: u64) -> &mut Self {
        self.instruction.lockup_id = Some(lockup_id);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn new_cap(&mut self, new_cap: u64) -> &mut Self {
        self.instruction.new_cap = Some(new_cap);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdateDepositCapInstructionArgs {
                                                              lockup_id: self.instruction.lockup_id.clone().expect("lockup_id is not set"),
                                                                  new_cap: self.instruction.new_cap.clone(),
                                    };
        let instruction = UpdateDepositCapCpi {
        __program: self.instruction.__program,
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          admin: self.instruction.admin.expect("admin is not set"),
                  
          settings: self.instruction.settings.expect("settings is not set"),
                  
          liquidity_pool: self.instruction.liquidity_pool.expect("liquidity_pool is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdateDepositCapCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            signer: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin: Option<&'b solana_account_info::AccountInfo<'a>>,
                settings: Option<&'b solana_account_info::AccountInfo<'a>>,
                liquidity_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                        lockup_id: Option<u64>,
                new_cap: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

