/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export type CreateVaultInstructionArgs = {
  minDeposit: beet.bignum
  minLockup: beet.bignum
  targetYieldRate: beet.bignum
  vaultSeed: beet.bignum
}
/**
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export const createVaultStruct = new beet.BeetArgsStruct<
  CreateVaultInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['minDeposit', beet.u64],
    ['minLockup', beet.i64],
    ['targetYieldRate', beet.u64],
    ['vaultSeed', beet.u64],
  ],
  'CreateVaultInstructionArgs'
)
/**
 * Accounts required by the _createVault_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] rtbProtocol
 * @property [_writable_] vault
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export type CreateVaultInstructionAccounts = {
  admin: web3.PublicKey
  rtbProtocol: web3.PublicKey
  vault: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createVaultInstructionDiscriminator = [
  29, 237, 247, 208, 193, 82, 54, 135,
]

/**
 * Creates a _CreateVault_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export function createCreateVaultInstruction(
  accounts: CreateVaultInstructionAccounts,
  args: CreateVaultInstructionArgs,
  programId = new web3.PublicKey('6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop')
) {
  const [data] = createVaultStruct.serialize({
    instructionDiscriminator: createVaultInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.rtbProtocol,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
