/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export const createVaultStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CreateVaultInstructionArgs'
)
/**
 * Accounts required by the _createVault_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] config
 * @property [_writable_] vault
 * @property [] depositMint
 * @property [] receiptMint
 * @property [_writable_] vaultPool
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export type CreateVaultInstructionAccounts = {
  signer: web3.PublicKey
  config: web3.PublicKey
  vault: web3.PublicKey
  depositMint: web3.PublicKey
  receiptMint: web3.PublicKey
  vaultPool: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createVaultInstructionDiscriminator = [
  29, 237, 247, 208, 193, 82, 54, 135,
]

/**
 * Creates a _CreateVault_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CreateVault
 * @category generated
 */
export function createCreateVaultInstruction(
  accounts: CreateVaultInstructionAccounts,
  programId = new web3.PublicKey('6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop')
) {
  const [data] = createVaultStruct.serialize({
    instructionDiscriminator: createVaultInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.receiptMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
