/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { DepositArgs, depositArgsBeet } from '../types/DepositArgs'

/**
 * @category Instructions
 * @category Deposit
 * @category generated
 */
export type DepositInstructionArgs = {
  args: DepositArgs
}
/**
 * @category Instructions
 * @category Deposit
 * @category generated
 */
export const depositStruct = new beet.BeetArgsStruct<
  DepositInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', depositArgsBeet],
  ],
  'DepositInstructionArgs'
)
/**
 * Accounts required by the _deposit_ instruction
 *
 * @property [**signer**] signer
 * @property [] vault
 * @property [] pool
 * @property [] depositToken
 * @property [_writable_] signerDepositTokenAccount
 * @property [] receiptToken (optional)
 * @property [_writable_] signerReceiptTokenAccount (optional)
 * @category Instructions
 * @category Deposit
 * @category generated
 */
export type DepositInstructionAccounts = {
  signer: web3.PublicKey
  vault: web3.PublicKey
  pool: web3.PublicKey
  depositToken: web3.PublicKey
  signerDepositTokenAccount: web3.PublicKey
  receiptToken?: web3.PublicKey
  signerReceiptTokenAccount?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const depositInstructionDiscriminator = [
  242, 35, 198, 137, 82, 225, 242, 182,
]

/**
 * Creates a _Deposit_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Deposit
 * @category generated
 */
export function createDepositInstruction(
  accounts: DepositInstructionAccounts,
  args: DepositInstructionArgs,
  programId = new web3.PublicKey('6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop')
) {
  const [data] = depositStruct.serialize({
    instructionDiscriminator: depositInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.pool,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.depositToken,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signerDepositTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.receiptToken ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signerReceiptTokenAccount ?? programId,
      isWritable: accounts.signerReceiptTokenAccount != null,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
