/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CompleteWithdraw
 * @category generated
 */
export const completeWithdrawStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CompleteWithdrawInstructionArgs'
)
/**
 * Accounts required by the _completeWithdraw_ instruction
 *
 * @property [_writable_, **signer**] user
 * @property [_writable_] lockup
 * @property [_writable_] vault
 * @property [_writable_] lockupReceiptTokenAccount
 * @property [_writable_] userDepositTokenAccount
 * @property [_writable_] depositPool
 * @property [_writable_] rewardPool
 * @property [_writable_] receiptMint
 * @category Instructions
 * @category CompleteWithdraw
 * @category generated
 */
export type CompleteWithdrawInstructionAccounts = {
  user: web3.PublicKey
  lockup: web3.PublicKey
  vault: web3.PublicKey
  lockupReceiptTokenAccount: web3.PublicKey
  userDepositTokenAccount: web3.PublicKey
  depositPool: web3.PublicKey
  rewardPool: web3.PublicKey
  receiptMint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const completeWithdrawInstructionDiscriminator = [
  172, 129, 141, 17, 95, 253, 251, 98,
]

/**
 * Creates a _CompleteWithdraw_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CompleteWithdraw
 * @category generated
 */
export function createCompleteWithdrawInstruction(
  accounts: CompleteWithdrawInstructionAccounts,
  programId = new web3.PublicKey('6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop')
) {
  const [data] = completeWithdrawStruct.serialize({
    instructionDiscriminator: completeWithdrawInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.lockup,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lockupReceiptTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userDepositTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rewardPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.receiptMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
