/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RequestWithdraw
 * @category generated
 */
export type RequestWithdrawInstructionArgs = {
  receiptAmount: beet.bignum
}
/**
 * @category Instructions
 * @category RequestWithdraw
 * @category generated
 */
export const requestWithdrawStruct = new beet.BeetArgsStruct<
  RequestWithdrawInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['receiptAmount', beet.u64],
  ],
  'RequestWithdrawInstructionArgs'
)
/**
 * Accounts required by the _requestWithdraw_ instruction
 *
 * @property [_writable_] vault
 * @property [_writable_, **signer**] withdrawRequest
 * @property [_writable_, **signer**] requester
 * @property [_writable_] receiptTokenAccount
 * @category Instructions
 * @category RequestWithdraw
 * @category generated
 */
export type RequestWithdrawInstructionAccounts = {
  vault: web3.PublicKey
  withdrawRequest: web3.PublicKey
  requester: web3.PublicKey
  receiptTokenAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const requestWithdrawInstructionDiscriminator = [
  137, 95, 187, 96, 250, 138, 31, 182,
]

/**
 * Creates a _RequestWithdraw_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RequestWithdraw
 * @category generated
 */
export function createRequestWithdrawInstruction(
  accounts: RequestWithdrawInstructionAccounts,
  args: RequestWithdrawInstructionArgs,
  programId = new web3.PublicKey('6ZZ1sxKGuXUBL8HSsHqHaYCg92G9VhMNTcJv1gFURCop')
) {
  const [data] = requestWithdrawStruct.serialize({
    instructionDiscriminator: requestWithdrawInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.withdrawRequest,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.requester,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.receiptTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
